version: '3'

services:
  spring-boot-jpa-app:
    image: booking_system_docker
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8087:8080
    volumes:
      - /data/spring-boot-app