spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: @datasource.password@
        url: @datasource.url@
        username: @datasource.username@
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        properties:
            hibernate:
                format_sql: true